---
title: "State Collection of Local Government Public Finance Data"
date: "2017-03-31"
categories: [data]
aliases:
  - /2017/03/31/local-gov-data/
---

In a conversation with a few colleagues, the question came up of which states collect public finance data on their respective local governments. Over the years, I have been keeping a list of such resources just in case I might want/need to use the data for a project. It dawned on me that I probably should not be hoarding this resource.

#### Arizona

No statewide datasets; however, there are a number of cities with open data portals. For instance,

* [City of Phoenix Open Data Portal](https://www.phoenix.gov/opendata)
* [City of Tucson  Open Data Portal](https://data.tucsonaz.gov/)

#### California 

* California State Controller’s Office Local Government Data Portal
  * Cities, Counties, & Special Districts
  * 2003-2016
  * [California State Controller’s Office](https://bythenumbers.sco.ca.gov/explore-all-data)
* Assessed Valuation Raw Data
  * Cities, Counties, & Special Districts
  * 2003-2016
  * [California State Controller’s Office](https://bythenumbers.sco.ca.gov/Raw-Data/Assessed-Valuation-Raw-Data-for-Fiscal-Years-2003-/qky3-f2m4)

#### Colorado
* Active Colorado Local Government Finances
  * Cities, Counties, School Districts, & Special Districts
  * Various years
  * [Colorado Department of Local Affairs](https://dola.colorado.gov/lgis/lgFinances.jsf;jsessionid=5b697b611a00513633ac35e75f91)

#### Connecticut

* Municipal Fiscal Indicators
  * Cities & Towns
  * 2003-2015
  * [CT Office of Policy & Management](http://www.ct.gov/opm/cwp/view.asp?a=2984&q=383170&opmNav_GID=1807)
* Equalized Net Grand List (Property Tax Valuations)
  * Cities & Towns
  * 2008-2014
  * [CT Office of Policy & Management](http://www.ct.gov/opm/cwp/view.asp?a=2987&q=385970&opmNav_GID=1807)
* Grand List Millage Rates
  * Cities & Towns
  * 2011-2015
  * [CT Office of Policy & Management](http://www.ct.gov/opm/cwp/view.asp?a=2987&q=385976&opmNav_GID=1807)

#### Florida 

* Local Government Financial Reporting
  * Cities & Counties
  * 1993-2016
  * [FL Chief Financial Officer](https://apps.fldfs.com/LocalGov/Reports/)
* Ad Valorem Tax Profiles
  * Cities, Counties, & School Districts
  * 1995/1996/1997-2015
  * [FL Office of Economic & Demographic Research](http://www.edr.state.fl.us/Content/local-government/data/data-a-to-z/a-f.cfm)

#### Georgia 

* Report of Local Government Finances
  * Cities & Counties
  * 1990-2016
  * [GA Department of Community Affairs](http://www.dca.state.ga.us/development/research/programs/lgf.asp)
* Tax Digest Consolidated Summary
  * Cities, Counties, & School Districts
  * 1990-2016
  * [GA Department of Revenue](https://apps.dor.ga.gov/digestconsolidation/default.aspx)

#### Illinois 

* Financial Databases
  * Cities & Counties
  * 1994-2015
  * [IL Comptroller Local Government Division](https://illinoiscomptroller.gov/services/local-government-division/financial-databases/?startRow=1&nextNID=9B25798B-4375-4309-975674A331173DCD)

#### Indiana 

* Annual Financial Reports
  * Cities, Towns, Townships, Counties, School Districts, & Special Districts
  * 2011-2016
  * [IN Gateway for Government Units](https://gateway.ifionline.org/report_builder/Default2.aspx?rptType=afr&rptVer=a)
* Assessed Value
  * Counties
  * 2016-2017
  * [IN Gateway for Government Units](https://gateway.ifionline.org/report_builder/Default2.aspx?rptType=assessedValue&rptVer=a)
* Government Financial and Tax Reports
  * Cities, Towns, Townships, Counties, School Districts, & Special Districts
  * Various years
  * [IN Gateway for Government Units](https://gateway.ifionline.org/report_builder/)

#### Iowa 

* City Budget and Actual Expenditures
  * Cities
  * 2007-2017
  * [data.iowa.gov](https://data.iowa.gov/Government/City-Budget-and-Actual-Expenditures/jy6h-2e5x)
* Consolidated Property Tax Rates
  * All taxing districts
  * 2002-2017
  * [data.iowa.gov](https://data.iowa.gov/Government/Consolidated-Property-Tax-Rates-by-Tax-District-An/7uts-ky8c)
* Taxable Property Values By Tax District
  * All taxing districts
  * 2000-2013 (see data note)
  * [data.iowa.gov](https://data.iowa.gov/Government/Taxable-Property-Values-By-Tax-District-and-Year/ig9g-pba5/)

#### Michigan

* Online Audit Reports
  * Cities, Counties, Townships, & Villages
  * Numerous years
  * [Michigan Department of Treasury Local Audit & Finance Division](https://treas-secure.state.mi.us/LAFDocSearch/)
* Office of Audits - Financial Statements
  * School Districts
  * 2009-2016
  * [Michigan Department of Education Office of Audits](https://civilservice.state.mi.us/nxt/gateway.dll?f=templates&fn=default.htm&vid=mofa:fa)

#### Missouri 

* Data Summary Report
  * Cities, Counties, Townships, & Villages
  * 2005-2016
  * [Missouri Department of Treasury](https://f65.mitreasury.msu.edu/Reports/DataSummaryReport.aspx)

#### North Carolina

* North Carolina County & Municipal Financial Information
  * Cities & Counties
  * 2008-2016
  * [NC Treasurer](https://www.nctreasurer.com/slg/lfm/financial-analysis/Pages/Analysis-by-Population.aspx)

#### Pennsylvania

* County Annual Financial Reports
  * Counties
  * 1986-2014
  * [PA DCED Munstat](http://munstats.pa.gov/Reports/ReportInformation2.aspx?report=cAfrForm)
* Municipal Annual Financial Reports
  * Cities
  * 1986-2014
  * [PA DCED Munstat](http://munstats.pa.gov/Reports/ReportInformation2.aspx?report=mAfrForm)

#### Virginia 

* Local Revenue/Expenditures/Capital Expenditures of Virginia’s Counties & Cities
  * Cities & Counties
  * 2002-2008
  * [VA Department of Housing an Community Development - Commission on Local Government ](http://www.dhcd.virginia.gov/index.php/commission-on-local-government/reports.html#Public-Finance)

If you know of anything missing or a link is dead, please let me know. I will happily update the list (if I can).
