---
title: "The Truth about Honesty in the Nonprofit Sector"
author: 
    - name: 
        given: Bruce D.
        family: McDonald
        literal: Bruce D. McDonald, III
      url: http://www.brucemcdonald.com/
      orcid: 0000-0001-8963-8606
      affiliation: North Carolina State University
    - name: 
        given: Christopher B.
        family: Goodman
        literal: Christopher B. Goodman
      url: https://www.cgoodman.com
      orcid: 0000-0002-8565-9714
      affiliation: Northern Illinois University
date: "2021-05-13"
pub-info:
  reference: >-
    <a href="http://www.brucemcdonald.com/">Bruce D. McDonald, III</a> and <strong>Christopher B. Goodman</strong> (2021). “The Truth about Honesty in the Nonprofit Sector,” <em>Public Administration Quarterly</em> 45 (2): 188-210, doi: <a href="https://doi.org/10.37808/paq.45.2.4" target="_blank" rel="noopener noreferrer"><code>10.37808/paq.45.2.4</code></a>
  links:
    - name: Preprint
      url: "../../files/papers/npo-benfords.pdf"
      icon: bi-file-earmark-pdf-fill
      local: true
    - name: Final version
      url: https://doi.org/10.37808/paq.45.2.4
      icon: bi-box-arrow-up-right
    - name: Add to Zotero
      url: https://www.zotero.org/save?type=doi&q=10.37808/paq.45.2.4
      icon: ai ai-zotero-square
categories:
    - benfords law
    - financial management
doi: 10.37808/paq.45.2.4
citation:
  type: article-journal
  title: "The truth about honesty in the nonprofit sector"
  container-title: "Public Administration Quarterly"
  issued: 2021
  volume: 45
  issue: 2
  page-first: 188
  page-last: 210
  url: https://paq.spaef.org/article/1984/The-Truth-about-Honesty-in-the-Nonprofit-Sector
google-scholar: true
---

### Abstract 
The nonprofit sector aims to provide services with a public benefit, but how honest is it? Since the nonprofit sector relies on fundraising efforts to support its administration and program costs, and since poor financial performance can scare potential contributors away, nonprofit organizations have an incentive to appear fiscally healthy regardless of their true condition. We examine the factors associated with the honesty of organizations in the nonprofit sector using Benford's Law, which tests for abnormalities in data that result from intentional falsification. Using the 990 tax filings for 51,010 nonprofits in the United States from 2012 and 2013, we find evidence of problems in the accuracy of their financial reporting. Those organizations with more external users of their financial information tend to conform more closely with Benford's Law, suggesting more external monitoring of non-profit organizations may decrease the likelihood of misreported financial information.