---
title: "The Fiscal Impacts of Urban Sprawl: Evidence from U.S. County Areas"
author: 
    - name: 
        given: Christopher B.
        family: Goodman
        literal: Christopher B. Goodman
      url: https://www.cgoodman.com
      orcid: 0000-0002-8565-9714
      affiliation: Northern Illinois University
date: "2019-12-01"
pub-info:
  reference: >-
    <strong>Christopher B. Goodman</strong> (2019) "The Fiscal Impacts of Urban Sprawl: Evidence from U.S. County Areas." <em>Public Budgeting &amp; Finance</em> 39 (4): 3-27., doi: <a href="https://doi.org/10.1111/pbaf.12239" target="_blank" rel="noopener noreferrer"><code>10.1111/pbaf.12239</code></a>
  links:
    - name: Preprint
      url: "../../files/papers/national-sprawl-expenditures.pdf"
      icon: fa-solid fa-file-pdf
      local: true
    - name: Final version
      url: https://doi.org/10.1111/pbaf.12239
      icon: fa-solid fa-arrow-up-right-from-square
    - name: Add to Zotero
      url: https://www.zotero.org/save?type=doi&q=10.1111/pbaf.12239
      icon: ai ai-zotero-square
categories:
    - sprawl
    - expenditures
    - fiscal impact
doi: 10.1111/pbaf.12239
citation:
  type: article-journal
  title: "The fiscal impacts of urban sprawl: evidence from U.S. county areas"
  container-title: "Public Budgeting & Finance"
  issued: 2019
  volume: 39
  issue: 4
  page-first: 3
  page-last: 27
  url: https://onlinelibrary.wiley.com/doi/10.1111/pbaf.12239
google-scholar: true
---

### Media Coverage
- [Why your sprawling, low-density suburb may be costing your local government money](https://blogs.lse.ac.uk/usappblog/2019/10/18/why-your-sprawling-low-density-suburb-may-be-costing-your-local-government-money/), *LSE USAPP Blog*, October 18, 2019.

### Abstract
This paper examines the fiscal impacts of urban development patterns in the United States. Previous studies have indicated that it is costly to provide public services in areas with low‐density, spatially expansive development, leading to higher per capita expenditures. However, theory would suggest alternate outcomes. This paper examines this question using a panel dataset of U.S. urban county areas and a specification allowing for potential nonlinearity between development patterns and per capita expenditures. Estimates indicate that the spatial extent of development is the most important factor in expenditures; it is less costly to provide public services when development is more compact. Higher density increases per capita expenditures; however, the effects are small.