---
title: "Local Government Fragmentation and the Local Public Sector: A Panel Data Analysis"
author: 
    - name: 
        given: Christopher B.
        family: Goodman
        literal: Christopher B. Goodman
      url: https://www.cgoodman.com
      orcid: 0000-0002-8565-9714
      affiliation: Northern Illinois University
date: "2015-01-01"
pub-info:
  reference: >-
    <strong>Christopher B. Goodman</strong>. (2015). “Local Government Fragmentation and the Local Public Sector: A Panel Data Analysis" <em>Public Finance Review</em> 43 (1): 82-107, doi: <a href="https://doi.org/10.1177/1091142113515048" target="_blank" rel="noopener noreferrer"><code>10.1177/1091142113515048</code></a>
  links:
    - name: Preprint
      url: "../../files/papers/frag-exp.pdf"
      icon: bi-file-earmark-pdf-fill
      local: true
    - name: Final version
      url: https://doi.org/10.1177/1091142113515048
      icon: bi-box-arrow-up-right
    - name: Add to Zotero
      url: https://www.zotero.org/save?type=doi&q=10.1177/1091142113515048
      icon: ai ai-zotero-square
categories:
    - fragmentation
    - expenditures
doi: 10.1177/1091142113515048
citation:
  type: article-journal
  title: "Local government fragmentation and the local public sector: a panel data analysis"
  container-title: "Public Finance Review"
  issued: 2015
  volume: 43
  issue: 1
  page-first: 82
  page-last: 107
  url: https://journals.sagepub.com/doi/10.1177/1091142113515048
google-scholar: true
---

### Abstract
This study analyzes the influence of fragmentation and concentration variables on per capita direct expenditures for all counties in the United States from 1982 to 2002. Building on recent research, fragmentation and concentration variables are developed to incorporate the horizontal as well as the vertical dimensions. This analysis explicitly takes into account the potential simultaneity between individual preferences for the spatial arrangement of local governments and the size of the local public sector using the element of time. The findings suggest that increased levels of fragmentation lead to an enlargement of the local public sector; however, the results are more complex than expected. Similarly, the concentration of service delivery responsibilities into counties and single purpose districts tends to increase the size of the local public sector.