---
title: "Political Fragmentation & Economic Growth in U.S. Metropolitan Areas"
author: 
    - name: 
        given: Christopher B.
        family: Goodman
        literal: Christopher B. Goodman
      url: https://www.cgoodman.com
      orcid: 0000-0002-8565-9714
      affiliation: Northern Illinois University
date: "2021-10-28"
pub-info:
  reference: >-
    <strong>Christopher B. Goodman</strong> (2021). “Political Fragmentation & Economic Growth in U.S. Metropolitan Areas,” <em>Journal of Urban Affairs</em> 43 (9): 1355-1376, doi: <a href="https://doi.org/10.1080/07352166.2020.1742578" target="_blank" rel="noopener noreferrer"><code>10.1080/07352166.2020.1742578</code></a>
  links:
    - name: Preprint
      url: "../../files/papers/frag-grow.pdf"
      icon: bi-file-earmark-pdf-fill
      local: true
    - name: Final version
      url: https://doi.org/10.1080/07352166.2020.1742578
      icon: bi-box-arrow-up-right
    - name: Add to Zotero
      url: https://www.zotero.org/save?type=doi&q=10.1080/07352166.2020.1742578
      icon: ai ai-zotero-square
categories:
    - growth 
    - decentralization 
    - fragmentation
    - competition
doi: 10.1080/07352166.2020.1742578
citation:
  type: article-journal
  title: "Political fragmentation & economic growth in U.S. metropolitan areas"
  container-title: "Journal of Urban Affairs"
  issued: 2021
  volume: 43
  issue: 9
  page-first: 1355
  page-last: 1376
  url: https://www.tandfonline.com/doi/full/10.1080/07352166.2020.1742578
google-scholar: true
---

### Media Coverage
- [The structure of US local governments is often a poor predictor of local economic growth](https://blogs.lse.ac.uk/usappblog/2021/11/17/the-structure-of-us-local-governments-is-often-a-poor-predictor-of-local-economic-growth/), *LSE USAPP Blog*, November 17, 2021.

### Abstract
This paper analyzes the impact of local political fragmentation on population, employment, and per capita money income growth in 314 U.S. metropolitan areas. The results are mixed. Smaller central cities and more special district overlap are important for population growth. The findings do not generalize to employment or per capita money income growth. These findings mask important regional variation: political fragmentation is largely unrelated to economic growth in Midwestern and Western metropolitan areas. These results partially support the hypothesis that governmental fragmentation can enhance local economic growth; however, the overall impact appears muted relative to a metropolitan area's economic characteristics.  