---
title: "House Prices and Property Tax Revenues During the Boom and Bust: Evidence from Small-Area Estimates"
author: 
    - name: 
        given: Christopher B.
        family: Goodman
        literal: Christopher B. Goodman
      url: https://www.cgoodman.com
      orcid: 0000-0002-8565-9714
      affiliation: Northern Illinois University
date: "2018-12-07"
pub-info:
  reference: >-
    <strong>Christopher B. Goodman</strong> (2018). “House Prices and Property Tax Revenues During the Boom and Bust: Evidence from Small-Area Estimates,” <em>Growth &amp; Change</em>, 49 (4): 636-656, doi: <a  href="https://doi.org/10.1111/grow.12261" target="_blank" rel="noopener noreferrer"><code>10.1111/grow.12261</code></a>
  links:
    - name: Preprint
      url: "../../files/papers/hp_pt.pdf"
      icon: bi-file-earmark-pdf-fill
      local: true
    - name: Final version
      url: https://doi.org/10.1111/grow.12261
      icon: bi-box-arrow-up-right
    - name: Add to Zotero
      url: https://www.zotero.org/save?type=doi&q=10.1111/grow.12261
      icon: ai ai-zotero-square
categories:
    - house prices
    - property tax
doi: 10.1111/grow.12261
citation:
  type: article-journal
  title: "House prices and property tax revenues during the boom and bust: evidence from small-area estimates"
  container-title: "Growth & Change"
  issued: 2018
  volume: 49
  issue: 4
  page-first: 636
  page-last: 656
  url: https://onlinelibrary.wiley.com/doi/10.1111/grow.12261
google-scholar: true
---

### Abstract
Although the Great Recession put the U.S. economy into a tailspin, we know little about how the changes in house prices influenced property tax collections. Using local level housing data from Zillow{{< iconify fa6-regular registered size=0.8em title='Registered' >}} matched to property tax data from 1998 to 2012, two questions are examined. First, the elasticity of property tax revenue with respect to house values is estimated. Second, the timing of this elasticity is determined. The analysis rules out that local policymakers capture the entire increase of house value in property tax revenues but unable to rule out that increases in house values are completely offset by changes in effective property tax rates. Decreases in values have an elasticity between 0.3 and 0.4 and take three years for changes in values to impact property tax revenues. While property tax collections declined, local policymakers adjusted effective millage rates such that revenues did not decline as much as home values.
