---
title: "Jurisdictional Overlap & the Size of the Local Public Workforce"
author:
    - name: 
        given: Christopher B.
        family: Goodman
        literal: Christopher B. Goodman
      url: https://www.cgoodman.com
      orcid: 0000-0002-8565-9714
      affiliation: Northern Illinois University
date: "2018-07-14"
pub-info:
  reference: >-
    <strong>Christopher B. Goodman</strong>. (2018). “Jurisdictional Overlap & the Size of the Local Public Workforce,” <em>State and Local Government Review</em>, 50 (1): 15-23 doi: <a href="https://doi.org/10.1177/0160323X18774402" target="_blank" rel="noopener noreferrer"><code>10.1177/0160323X18774402</code></a>
  links:
    - name: Preprint
      url: "../../files/papers/frag-employ.pdf"
      icon: fa-solid fa-file-pdf
      local: true
    - name: Final version
      url: https://doi.org/10.1177/0160323X18774402
      icon: fa-solid fa-arrow-up-right-from-square
categories:
    - Public employment
    - Tiebout
    - Competition
doi: 10.1177/0160323X18774402
citation:
  type: article-journal
  title: "Jurisdictional overlap & the size of the local public workforce"
  container-title: "State & Local Government Review"
  issued: 2018
  volume: 50
  issue: 1
  page-first: 15
  page-last: 23
  url: https://journals.sagepub.com/doi/10.1177/0160323X18774402
google-scholar: true
---

### Abstract
The United States is a country of many overlapping local governments. Theoretical explorations of the potential influence of this institutional arrangement abound; however, empirical evidence as the influence of such an arrangement on local public sector remains relatively thin. Instead of competing for mobile resources as suggested by Tiebout, overlapping jurisdictions utilize similar tax and voting bases introducing a potential commons problem. Using a county-level dataset from 1972 to 2012, this commons problem is explored. The results suggest that a positive relationship between jurisdictional overlap and the size of local public workforce amounting to approximately a one percent increase in employment or an increase of less than one full-time equivalent employee.
