---
title: "Tensions in State-Local Intergovernmental Response to Emergencies: The Case of COVID-19"
author: 
    - name: 
        given: Bruce D.
        family: McDonald
        literal: Bruce D. McDonald, III
      url: http://www.brucemcdonald.com/
      orcid: 0000-0001-8963-8606
      affiliation: North Carolina State University
    - name: 
        given: Christopher B.
        family: Goodman
        literal: Christopher B. Goodman
      url: https://www.cgoodman.com
      orcid: 0000-0002-8565-9714
      affiliation: Northern Illinois University
    - name: 
        given: Megan E.
        family: Hatch
        literal: Megan E. Hatch
      url: https://facultyprofile.csuohio.edu/csufacultyprofile/detail.cfm?FacultyID=m_e_hatch
      orcid: 0000-0001-5201-4066
      affiliation: Cleveland State University
date: "2020-09-01"
pub-info:
  reference: >-
    <a href="http://www.brucemcdonald.com/">Bruce D. McDonald, III</a>, <strong>Christopher B. Goodman</strong>, and <a href="https://facultyprofile.csuohio.edu/csufacultyprofile/detail.cfm?FacultyID=m_e_hatch">Megan E. Hatch</a>, (2020). “State Tensions in State-Local Intergovernmental Response to Emergencies: The Case of COVID-19,” <em>State and Local Government Review</em> 52 (3): 186-194, doi: <a href="https://doi.org/10.1177/0160323X20979826" target="_blank" rel="noopener noreferrer"><code>10.1177/0160323X20979826</code></a>
  links:
    - name: Preprint
      url: "../../files/papers/covidpreemption.pdf"
      icon: bi-file-earmark-pdf-fill
      local: true
    - name: Final version
      url: https://doi.org/10.1177/0160323X20979826
      icon: bi-box-arrow-up-right
    - name: Add to Zotero
      url: https://www.zotero.org/save?type=doi&q=10.1177/0160323X20979826
      icon: ai ai-zotero-square
categories:
    - preemption
    - intergovernmental affairs
    - emergency management
doi: 10.1177/0160323X20979826
citation:
  type: article-journal
  title: "Tensions in state-local intergovernmental response to emergencies: the case of COVID-19"
  container-title: "State & Local Government Review"
  issued: 2020
  volume: 52
  issue: 3
  page-first: 186
  page-last: 194
  url: https://journals.sagepub.com/doi/10.1177/0160323X20979826
google-scholar: true
---

### Abstract
The U.S. emergency and disaster response system is designed to operate bottom-up, meaning responses are intended to begin at the local level with state and federal governments stepping in to assist as needed. The response to the current COVID-19 outbreak, however, has been something else entirely, as each level of government competes with the others over resources and authority. Some states preferred a local response with state support, while other states took a more uniform, state-mandated response enabled by state preemption of local actions. The latter has revealed an often-dormant means of state preemption of local ordinances: the executive order preemption. Local government managers will have to be creative in balancing responsiveness to their constituents in this time of crisis while also being constrained by their states. The administrative choices are likely to have both immediate and long-term consequences for future emergencies.

