---
title: "State Preemption of Local Laws: Origins and Modern Trends"
author: 
    - name: 
        given: Christopher B.
        family: Goodman
        literal: Christopher B. Goodman
      url: https://www.cgoodman.com
      orcid: 0000-0002-8565-9714
      affiliation: Northern Illinois University
    - name: 
        given: Megan E.
        family: Hatch
        literal: Megan E. Hatch
      url: https://facultyprofile.csuohio.edu/csufacultyprofile/detail.cfm?FacultyID=m_e_hatch
      orcid: 0000-0001-5201-4066
      affiliation: Cleveland State University
    - name: 
        given: Bruce D.
        family: McDonald
        literal: Bruce D. McDonald, III
      url: http://www.brucemcdonald.com/
      orcid: 0000-0001-8963-8606
      affiliation: North Carolina State University
date: "2021-06-01"
pub-info:
  reference: >-
    <strong>Christopher B. Goodman</strong>, <a href="https://facultyprofile.csuohio.edu/csufacultyprofile/detail.cfm?FacultyID=m_e_hatch">Megan E. Hatch<a/>, and <a href="http://www.brucemcdonald.com/">Bruce D. McDonald, III</a> (2021). “State Preemption of Local Laws: Origins and Modern Trends,” <em>Perspectives on Public Management & Governance</em> 4 (2): 146-158, doi: <a href="https://doi.org/10.1093/ppmgov/gvaa018" target="_blank" rel="noopener noreferrer"><code>10.1093/ppmgov/gvaa018</code></a>
  links:
    - name: Preprint
      url: "../../files/papers/preemption-history.pdf"
      icon: fa-solid fa-file-pdf
      local: true
    - name: Final version
      url: https://doi.org/10.1093/ppmgov/gvaa018
      icon: fa-solid fa-arrow-up-right-from-square
    - name: Add to Zotero
      url: https://www.zotero.org/save?type=doi&q=10.1093/ppmgov/gvaa018
      icon: ai ai-zotero-square
categories:
    - preemption
    - intergovernmental affairs
doi: 10.1093/ppmgov/gvaa018
citation:
  type: article-journal
  title: "State preemption of local laws: origins and modern trends"
  container-title: "Perspectives on Public Management & Governance"
  issued: 2021
  volume: 4
  issue: 2
  page-first: 146
  page-last: 158
  url: https://academic.oup.com/ppmg/article-abstract/4/2/146/5919501
google-scholar: true
---

### Abstract 

American cities are creatures of their states, with states both granting and limiting the power of their cities. This relationship is characterized by how cooperative or competitive states are with cities in their legislation. Despite the recent attention given to state preemption of local laws, this is not a new phenomenon. Part of the confusion surrounding preemption is that there is no shared definition or understanding of its forms. The purpose of this article is to begin to create that shared conception. In doing so, we define preemption according to its historic origins as the use of coercive methods to substitute state priorities for local policymaking. We argue modern state preemption of local laws can be divided into four phases, each with their own policies and mechanisms. We show how preemption has changed over time, shifting the functional, legal, and political relationship between states and their cities. Together, these phases help assist policymakers and administrators in understanding the nature of state preemption, and thus how to create and implement local policies in an environment where the distribution of power between governments is competitive and changing.