---
title: "What Lies Beneath These Creatures of the State: Understanding the Death of Specialised Governments in the U.S"
author: 
    - name: 
        given: Christopher B.
        family: Goodman
        literal: Christopher B. Goodman
      url: https://www.cgoodman.com
      orcid: 0000-0002-8565-9714
      affiliation: Northern Illinois University
    - name: 
        given: Suzanne M.
        family: Leland
        literal: Suzanne M. Leland
      url: https://pages.charlotte.edu/suzanne-leland/
      affiliation: University of North Carolina at Charlotte
date: "2025-01-01"
pub-info:
  reference: >-
    <strong>Christopher B. Goodman</strong> and <a href="https://pages.charlotte.edu/suzanne-leland/">Suzanne M. Leland</a>. (<em>Forthcoming</em>) “What Lies Beneath These Creatures of the State: Understanding the Death of Specialised Governments in the U.S” <em>Local Government Studies</em>. doi: <a href="https://doi.org/10.1080/03003930.2024.2360559" target="_blank" rel="noopener noreferrer"><code>10.1080/03003930.2024.2360559</code></a>
  links:
    - name: Preprint
      url: "../../files/papers/sd-dissolve.pdf"
      icon: fa-solid fa-file-pdf
      local: true
    - name: Final version
      url: https://doi.org/10.1080/03003930.2024.2360559
      icon: fa-solid fa-arrow-up-right-from-square
    - name: Add to Zotero
      url: https://www.zotero.org/save?type=doi&q=10.1080/03003930.2024.2360559
      icon: ai ai-zotero-square
categories:
    - Special districts
    - Dissolution
    - Intergovernmental affairs
doi: 10.1080/03003930.2024.2360559
citation:
  type: article-journal
  title: "What lies beneath these creatures of the state: understanding the death of specialised governments in the U.S"
  container-title: "Local Government Studies"
  issued: 2024-05-28
  #volume: 60
  #issue: 6
  #page-first: 1048
  #page-last: 1065
  url: https://doi.org/10.1080/03003930.2024.2360559
google-scholar: true
---

### Abstract
After analysing 40 years of census data on U.S. local government change, this study finds that the dissolution of special districts (specialised governments) or “exits” in U.S. counties are largely unrelated to demand factors. Using fixed effects regression specified at the urban county level, we find that restrictions on the fiscal autonomy of cities are associated with decreases in the special district exit rate and count. There is also evidence that state grants of “broad” or “limited” functional home rule to cities increase special district dissolutions. These results largely disappear when examining subgroups of districts classified by their asset specificity. The findings are consistent with the circumvention argument made in the local autonomy literature and may indicate some service consolidation, albeit from a different perspective. 