---
title: "Are Special Districts Strategic Complements or Strategic Substitutes?"
author: 
    - name: 
        given: Christopher B.
        family: Goodman
        literal: Christopher B. Goodman
      url: https://www.cgoodman.com
      orcid: 0000-0002-8565-9714
      affiliation: Northern Illinois University
    - name: 
        given: Deborah A.
        family: Carroll
        literal: Deborah A. Carroll
      url: https://gfrc.uic.edu/profiles/carroll-deborah/
      orcid: 0000-0002-3202-7019
      affiliation: University of Illinois at Chicago
date: "2024-06-24"
pub-info:
  reference: >-
    <strong>Christopher B. Goodman</strong> and <a href="https://gfrc.uic.edu/profiles/carroll-deborah/">Deborah A. Carroll</a>. (2024) “Are Special Districts Strategic Complements or Strategic Substitutes?” <em>Public Administration Review</em> 84 (4): 623--636, doi: <a href="https://doi.org/10.1111/puar.13672" target="_blank" rel="noopener noreferrer"><code>10.1111/puar.13672</code></a>
  links:
    - name: Preprint
      url: "../../files/papers/sd-gp.pdf"
      icon: fa-solid fa-file-pdf
      local: true
    - name: Final version
      url: https://doi.org/10.1111/puar.13672
      icon: fa-solid fa-arrow-up-right-from-square
    - name: Add to Zotero
      url: https://www.zotero.org/save?type=doi&q=10.1111/puar.13672
      icon: ai ai-zotero-square
categories:
    - Special districts
    - Public service provision 
    - Local government
doi: 10.1111/puar.13672
citation:
  type: article-journal
  title: "Are special districts strategic complements or strategic substitutes?"
  container-title: "Public Administration Review"
  issued: 2024-06-24
  volume: 84
  issue: 4
  page-first: 623
  page-last: 636
  url: https://onlinelibrary.wiley.com/doi/10.1111/puar.13672
google-scholar: true
---

### Abstract
What happens to general-purpose local government spending for service provision when a special district enters the public service market? Theoretically, special districts can act either as complements by supplementing existing service provision spending or as substitutes by supplanting current service provision spending. We find a substitution effect using fixed effects regression on urban counties in the United States from 1972 to 2017. Special districts replace spending for public service provision by county governments; however, we find no similar result for municipal governments. But the results are nuanced–findings are confined mainly to public services that tend to cover large land areas like fire protection, sewerage, and solid waste management. Furthermore, we find evidence that day-to-day operations drive observed substitution, and that county size is an important factor depending on the functional service area. 