---
title: "The Consequences of Specialized Governance on Spending and Expansion of Public Transit"
author: 
    - name: 
        given: Christopher B.
        family: Goodman
        literal: Christopher B. Goodman
      url: https://www.cgoodman.com
      orcid: 0000-0002-8565-9714
      affiliation: Northern Illinois University
    - name: 
        given: Suzanne M.
        family: Leland
        literal: Suzanne M. Leland
      affiliation: University of North Carolina at Charlotte
    - name: Olga Smirnova
      url: https://politicalscience.ecu.edu/about/faculty-staff/smirnova/
      affiliation: East Carolina University
date: "2021-04-01"
pub-info:
  reference: >-
    <strong>Christopher B. Goodman</strong>, <a href="https://pages.charlotte.edu/suzanne-leland/">Suzanne M. Leland</a>, and Olga Smirnova. (2021). “The Consequences of Specialized Governance on Spending and Expansion of Public Transit,” <em>Local Government Studies</em> 47 (2): 296-311, doi: <a href="https://doi.org/10.1080/03003930.2020.1744571" target="_blank" rel="noopener noreferrer"><code>10.1080/03003930.2020.1744571</code></a>
  links:
    - name: Preprint
      url: "../../files/papers/specialized-governance.pdf"
      icon: fa-solid fa-file-pdf
      local: true
    - name: Final version
      url: https://doi.org/10.1080/03003930.2020.1744571
      icon: fa-solid fa-arrow-up-right-from-square
categories:
    - Special districts
    - Issue salience
    - Transportation policy
doi: 10.1080/03003930.2020.1744571
citation:
  type: article-journal
  title: "The consequences of specialized governance on spending and expansion of public transit"
  container-title: "Local Government Studies"
  issued: 2021
  volume: 47
  issue: 2
  page-first: 2296
  page-last: 311
  url: https://journals.sagepub.com/doi/10.1177/0275074018804665
google-scholar: true
---

### Abstract

Special-purpose governments are commonly characterised as hidden governments with less taxpayer accountability and can issue debt. However, little research has been conducted to see if operating and capital expenses are driven by the public’s perception of need or are a policy consequence of functional specialisation. The following study tests how problem salience and form of government interact to impact local governments’ expenditures. We use National Transit Data (2013–2014) to test these moderating relationships. Our findings indicate that at least in the context of public transit, service area characteristics play a larger role in the spending and expansion than either the form of government or issue salience (as measured in this paper). This also indicates that the moderating effect of salience and governance does not appear to be significant for public transit policy.