---
title: "Assessing the Influence of Property Tax Delinquency and Foreclosures on Residential Property Sales"
author: 
    - name: 
        given: Deborah A.
        family: Carroll
        literal: Deborah A. Carroll
      url: https://gfrc.uic.edu/profiles/carroll-deborah/
      orcid: 0000-0002-3202-7019
      affiliation: University of Illinois at Chicago
    - name: 
        given: Christopher B.
        family: Goodman
        literal: Christopher B. Goodman
      url: https://www.cgoodman.com
      orcid: 0000-0002-8565-9714
      affiliation: Northern Illinois University
date: "2017-09-01"
pub-info:
  reference: >-
    <a href="https://gfrc.uic.edu/profiles/carroll-deborah/">Deborah A. Carroll</a> and <strong>Christopher B. Goodman</strong> (2017) "Assessing the Influence of Property Tax Delinquency and Foreclosures on Residential Property Sales." <em>Urban Affairs Review</em> 53 (5): 898-923, doi: <a href="https://doi.org/10.1177/1078087416678339" target="_blank" rel="noopener noreferrer"><code>10.1177/1078087416678339</code></a>
  links:
    - name: Preprint
      url: "../../files/papers/tax-delq.pdf"
      icon: fa-solid fa-file-pdf
      local: true
    - name: Final version
      url: https://doi.org/10.1177/1078087416678339
      icon: fa-solid fa-arrow-up-right-from-square
categories:
    - House prices
    - Tax delinquency
doi: 10.1177/1078087416678339
citation:
  type: article-journal
  title: "Assessing the influence of property tax delinquency and foreclosures on residential property sales"
  container-title: "Urban Affairs Review"
  issued: 2017
  volume: 53
  issue: 5
  page-first: 898
  page-last: 923
  url: https://journals.sagepub.com/doi/10.1177/1078087416678339
google-scholar: true
---

### Abstract
We examine the influence of property tax delinquency on the sale price of nearby homes from 2002 to 2013 using more than 46,000 residential property sales in a representative midwestern central city—Milwaukee, Wisconsin. After controlling for a number of property and neighborhood characteristics including nearby foreclosures, we find property tax delinquency has a significant influence on nearby home sales. The relationship is negative; one additional tax delinquent property within 250 m of a home sale is associated with a discounted sale price of 0.79% or approximately $1,085 on average. In addition, the influence of tax delinquent properties on home sale prices diminishes with distance, suggesting blight is the source of the discount. Based on these findings, the negative influence of tax delinquency is likely to be exacerbated in central cities where housing density is greater and delinquency is higher and more persistent than the surrounding suburbs, which has the potential to lead to fiscal distress as property taxes are the primary revenue source for cities. As such, we suggest a two-tiered approach for cities to mitigate the negative consequences of tax delinquency: a combination of policies to eliminate delinquency and also to help homeowners become financially stable.