---
title: "The Forgotten Governments: Exploring Midwestern Township Capacities and Functional Service Responsibilities"
author: 
    - name: "Jaehee Jong"
      orcid: 0000-0001-9546-6089
      affiliation: Northern Illinois University
    - name: 
        given: Christopher B.
        family: Goodman
        literal: Christopher B. Goodman
      url: https://www.cgoodman.com
      orcid: 0000-0002-8565-9714
      affiliation: Northern Illinois University
    - name: "Aaron Deslatte"
      orcid: 0000-0001-5518-3949
      affiliation: Indiana University
    - name: "Jerry Crabtree"
      affiliation: Township Officials of Illinois
    - name: "Kurt Thurmaier"
      affiliation: Northern Illinois University
date: "2023-06-01"
pub-info:
  reference: >-
    Jahee Jong, <strong>Christopher B. Goodman</strong>, Aaron Deslatte, Jerry Crabtree and Kurt Thurmaier. (2023). “The Forgotten Governments: Exploring Midwestern Township Capacities and Functional Service Responsibilities,” <em>State and Local Government Review</em> 55 (2): 170-184, doi: <a href="https://doi.org/10.1177/0160323X221124894" target="_blank" rel="noopener noreferrer"><code>10.1177/0160323X221124894</code></a>
  links:
    - name: Preprint
      url: "../../files/papers/townships.pdf"
      icon: fa-solid fa-file-pdf
      local: true
    - name: Final version
      url: https://doi.org/10.1177/0160323X221124894
      icon: fa-solid fa-arrow-up-right-from-square
    - name: Add to Zotero
      url: https://www.zotero.org/save?type=doi&q=10.1177/0160323X221124894
      icon: ai ai-zotero-square
categories:
    - Townships
doi: 10.1177/0160323X221124894    
citation:
  type: article-journal
  title: "The forgotten governments: exploring midwestern township capacities and functional service responsibilities"
  container-title: "State & Local Government Review"
  issued: 2023
  volume: 55
  issue: 2
  page-first: 170
  page-last: 184
  url: https://journals.sagepub.com/doi/10.1177/0160323X221124894
google-scholar: true
---

### Abstract
This field note provides both a foundation for discussion about the role of townships in local governance and empirical evidence of their unique and embedded role. Drawing on a survey administered to Illinois township supervisors, administrators, and assessors, it presents baseline indicators about the range of township services, managerial practices, assessment, and collaboration for services to better illuminate current services, capacities, and challenges. A greater understanding of the complexity of delivering township services can guide policymakers in their deliberations about the future of township governments and provide research propositions for investigating township governments in the United States.