---
title: "Creative Destruction? Examining Special District Dissolution by Service Area"
author: 
    - name: 
        given: Christopher B.
        family: Goodman
        literal: Christopher B. Goodman
      url: https://www.cgoodman.com
      orcid: 0000-0002-8565-9714
      affiliation: Northern Illinois University
    - name: 
        given: Suzanne M.
        family: Leland
        literal: Suzanne M. Leland
      url: https://pages.charlotte.edu/suzanne-leland/
      affiliation: University of North Carolina at Charlotte
date: "2025-01-01"
pub-info:
  reference: >-
    <strong>Christopher B. Goodman</strong> and <a href="https://pages.charlotte.edu/suzanne-leland/">Suzanne M. Leland</a>. "Creative Destruction? Examining Special District Dissolution by Service Area."
  extra: >-
    Presented at the annual meeting of the [Southern Political Science Association](https://slides.cgoodman.com/presentation/2025-spsa), San Juan, Puerto Rico, January 2025.
  #links:
  #  - name: Preprint
  #    url: "../../files/papers/sd-dissolve.pdf"
  #    icon: bi-file-earmark-pdf-fill
  #    local: true
  #  - name: Final version
  #    url: https://doi.org/10.1080/03003930.2024.2360559
  #    icon: bi-box-arrow-up-right
  #  - name: Add to Zotero
  #    url: https://www.zotero.org/save?type=doi&q=10.1080/03003930.2024.2360559
  #    icon: ai ai-zotero-square
categories:
    - special districts
    - dissolution
    - intergovernmental affairs
#doi: 10.1080/03003930.2024.2360559
citation:
  type: article
  title: "Functional Specialization and Special District Dissolution"
  #container-title: "Local Government Studies"
  #issued: 2024-05-28
  #volume: 60
  #issue: 6
  #page-first: 1048
  #page-last: 1065
  #url: https://doi.org/10.1080/03003930.2024.2360559
google-scholar: true
draft: false
---

### Abstract
Currently, the special district form of local government is the largest single form of local government in the United States at just over 38,000. Additionally, the growth of this form of local government has been much larger than any other form of government. However, this overall trend conceals an unusual underlying shift. While many special districts are created in any time period, many special districts are dissolved, consolidated, or merged. Little research has been conducted been conducted on this phenomenon. This research suggests economic changes as well as the state and local policy environment are important predictors of dissolution. However, special districts are typically highly specialized. Prior research has suggested that the functionally specialized nature of special districts makes analyzing dissimilar districts difficult. This research aims to address this issue by examining special district dissolution by the top four functional areas: Fire Districts, Housing & Community Development Districts, Natural Resource Districts, Water Districts.

Using data from the Census of Governments from 1977 to 2017, an empirical model of special district dissolution by functional area at the all-county and urban-county level is built. Consistent with the literature, covariates include economic and demographic characteristics, state laws governing general purpose local governments, and variables addressing the prevalence and recent success of boundary change entrepreneurs in the area. The findings suggest that the prevalence of boundary change entrepreneurs is largely unrelated to special district dissolution; however, prior success of entrepreneurs (as measured as entry rate of new districts in the functional area in the previous period) is largely indicative of an increased exit rate across all four functional areas. State laws and economic and demographic characteristics are sporadically influential and vary by functional area in their level of importance. Overall, this analysis provides important nuance to the nascent special district dissolution literature. 