---
title: "Are Special Districts Strategic Complements or Strategic Substitutes?"
author: 
    - name: Christopher B. Goodman
      url: https://www.cgoodman.com
      orcid: 0000-0002-8565-9714
      affiliation: Northern Illinois University
    - name: Deborah A. Carroll
      url: https://gfrc.uic.edu/profiles/carroll-deborah/
      orcid: 0000-0002-3202-7019
      affiliation: University of Illinois at Chicago
date: "2022-10-12"
pub-info:
  reference: >-
    <strong>Christopher B. Goodman</strong> and <a href="https://gfrc.uic.edu/profiles/carroll-deborah/">Deborah A. Carroll</a>. “Are Special Districts Strategic Complements or Strategic Substitutes?”
  links:
    - name: PDF
      url: "../../files/papers/sd-gp.pdf"
      icon: fa-solid fa-file-pdf
      local: true
categories:
    - Special districts
    - Public service provision 
    - Local government

---

## Abstract
What happens to service provision when a special district enters the public service market? Theoretically, special districts can act either as complements by supplementing existing service provision, or as substitutes by supplanting current service provision. We find a substitution effect using fixed effects regression on urban counties in the United States from 1972 to 2017. Special districts replace public service provision by county governments; however, we find no similar result for municipal governments. The results are nuanced – findings are confined mainly to spatially expansive public services like fire protection, sewerage, and solid waste management. Furthermore, we find evidence that day-to-day operations drive observed substitution and that county size is an important factor depending on the functional service area.

## BibTeX Citation
```bib
@unpublished{goodman-carroll-2022,
  author = {Goodman, Christopher B. and Carroll, Deborah A.},
  note = {Working Paper},
  title = {Are Special Districts Strategic Complements or Strategic Substitutes?},
  year = {2022}}
```
