---
title: "Patterns in Special District Creation and Dissolution"
author: 
    - name: Christopher B. Goodman
      url: https://www.cgoodman.com
      orcid: 0000-0002-8565-9714
      affiliation: Northern Illinois University
date: "2020-01-01"
pub-info:
  reference: >-
    <strong>Christopher B. Goodman</strong>. “Patterns in Special District Creation and Dissolution”
  links:
    - name: "{{< iconify bi file-earmark-pdf-fill size=1.1em title='PDF' >}} PDF"
      url: "../../files/papers/sd-io.pdf"
      local: true
categories:
    - Special districts
    - Dissolution
    - Creation
---

## Abstract
Special districts are a numerous and unique form of local government in the United States. Unlike cities, counties, and towns, special districts are created and dissolved often. Using tools from the industrial organizations literature, this analysis examines patterns in creation and dissolution of special districts using Census of Governments data from 1972 to 2017. Overall, the rate of entry (creation) has been declining over time while the rate of exit (dissolution) has remained steady. New districts tend to be small relative to existing districts and and exhibit slow growth over time. Lastly, special districts do not appear susceptible to the "liability of newness" or exhibit high levels of infant organizational mortality that is common in the private sector.

## BibTeX Citation
```bib
@unpublished{goodman-2020,
  author = {Goodman, Christopher B},
  note = {Working Paper},
  title = {Patterns in Special District Creation and Dissolution},
  year = {2020}}
```