---
title: "Overlapping Jurisdictions and Residential Segregation by Race"
author: 
    - name: 
        given: Christopher B.
        family: Goodman
        literal: Christopher B. Goodman
      url: https://www.cgoodman.com
      orcid: 0000-0002-8565-9714
      affiliation: Northern Illinois University
date: "2024-10-21"
pub-info:
  reference: >-
    <strong>Christopher B. Goodman</strong>. "Overlapping Jurisdictions and Residential Segregation by Race”
  extra: >-
    Presented at the annual meeting of the [Urban Affairs Association](https://slides.cgoodman.com/presentation/2023-uaa), Nashville, Tennessee, April 2023.
  #links:
  #  - name: PDF
  #    url: "../../files/papers/sd-io.pdf"
  #    icon: bi-file-earmark-pdf-fill
  #    local: true
categories:
    - special districts
    - intergovernmental affairs
citation:
  type: article
  title: "verlapping Jurisdictions and Residential Segregation by Race"
  url: https://www.cgoodman.com/research/working-papers/sd-segregation
google-scholar: true
draft: false
---

### Abstract
Anecdotal and empirical evidence suggests a link between municipal fragmentation and residential segregation between jurisdictions by race. As Tiebout (1956) suggested, a preponderance of local jurisdictions incentivizes individuals or households to “vote with their feet” and sort into communities that most closely satisfy their preferences. Also implied by Tiebout and increasingly becoming the dominant narrative, high-income and racially homogenous jurisdictions use land use regulations to lock in existing (segregated) patterns of human settlement. However, few municipalities are created in the United States. Significantly more overlapping local governments are created that can equally and perhaps more efficiently segregate local public services across space.  

This manuscript examines the role of special districts in residential segregation within and across jurisdictions. Using both urban county and MSA-level data from the U.S. Census, an empirical model is specified with particular attention paid to the potential endogeneity between patterns of residential segregation and local government fragmentation. Local government fragmentation is instrumented by geographic factors unrelated to segregation – rivers in the county/MSA and the average slope of the county/MSA. This manuscript intends to shed light on the potential outcomes of a relatively hidden yet important form of local government and its role in potentially perpetuating an unequal metropolis. 

