---
title: "Understanding and Measuring Elasticity, Volatility, and Implications for Local Government Fiscal Health"
author:
    - name: 
        given: Deborah A.
        family: Carroll
        literal: Deborah A. Carroll
      url: https://gfrc.uic.edu/profiles/carroll-deborah/
      orcid: 0000-0002-3202-7019
      affiliation: University of Illinois at Chicago
    - name: 
        given: Christopher B.
        family: Goodman
        literal: Christopher B. Goodman
      url: https://www.cgoodman.com
      orcid: 0000-0002-8565-9714
      affiliation: Northern Illinois University
date: 2013-01-01
pub-info:
  reference: >-
    Deborah A. Carroll and <strong>Christopher B. Goodman</strong>. (2012). "Understanding and Measuring Elasticity, Volatility, and Implications for Local Government Fiscal Health." In <em>Handbook of Local Government Fiscal Health</em>, edited by Jonathan B. Justice, Helisse Levine, and Eric Scorsone. Sudbury, MA: Jones and Bartlett, Inc. 
  links:
    - name: Add to Zotero
      url: https://www.zotero.org/save?type=isbn&q=9780763792305
      icon: ai ai-zotero-square
categories:
    - fiscal health
citation:
  type: chapter
  title: "Understanding and measuring elasticity, volatility, and implications for local government fiscal health"
  container-title: "Handbook of Local Government Fiscal Health"
  editor:
    - name:
        given: Jonathan B.
        family: Justice
        literal: Jonathan B. Justice
    - name:
        given: Helisse
        family: Levine
        literal: Helisse Levine
    - name:
        given: Eric
        family: Scorsone
        literal: Eric Scorsone
  issued: 2012
  publisher: "Jones and Bartlett, Inc."
  url: https://www.cgoodman.com/research/chapters/fiscal-health
google-scholar: true
---

### Abstract
The most recent fiscal crisis and resulting economic environment has posed serious implications for the fiscal health of local governments. Local governments have been struggling with manipulating revenue structures in response to shrinking tax bases and decreased consumer demand for taxable goods and services. Some local property markets have seen significant decreases in home values; something that was never expected to happen. Assessed values have fallen and tax delinquency has risen, thereby leading to decreased property tax revenues. Demand for both consumer goods and fee-based government services has declined as unemployment is up and consumers have tightened their belts to deal with the economic crisis, which has led to significant shortfalls in sales tax and user fee revenues. All of these effects of the economic crisis and state of the economy directly influence the performance of local government revenue structures and consequently affect local government fiscal health.