---
title: "The Role of Special Districts and Intergovernmental Constraints"
author: 
    - name: Christopher B. Goodman
      url: https://www.cgoodman.com
      orcid: 0000-0002-8565-9714
      affiliation: Northern Illinois University
date: "2023-09-01"
pub-info:
  reference: >-
    <strong>Christopher B. Goodman</strong>. (2023). "The Role of Special Districts and Intergovernmental Constraints." In <a href="https://www.e-elgar.com/shop/usd/research-handbook-on-city-and-municipal-finance-9781800372955.html" target="_blank" rel="noopener noreferrer"><em>Research Handbook on City and Municipal Finance</em></a>, edited by Justin M. Ross, Temirlan T. Moldogaziev, and Craig L. Johnson. Cheltenham, UK: Edward Elgar Publishing.
categories:
    - Special districts
    - Institutions
---

## Abstract
The United States’ federal system is awash in local governments. As of 2017, the year of the last complete Census of Governments, there are 90,075 independent units of local government. Among the various forms of local government used, a plurality is a form of special-purpose local government called a special district. These districts are often single function (but sometimes not), sometimes conform to city or county boundaries (but sometimes not), and overlap all other forms of local government, including other special districts. The services provided by special districts are typically not unique; general-purpose local governments often provide the same services in other areas. The three most common special district functions include fire protection, housing and community development, and water supply – all functions provided by general-purpose local governments. The initial setup begs the question: Why do special districts exist? Moreover, perhaps more pressing, what are the implications for local fiscal outcomes?

## BibTeX Citation
```bib
@incollection{goodman-2023-handbook,
  author = {Goodman, Christopher B.},
  address = {Cheltenham, UK},
  booktitle = {Research Handbook on City and Municipal Finance},
  editor = {Ross, Justin M. and Moldogaziev, Temirlan T. and Johnson, Craig L.},
  publisher = {Edward Elgar Publishing},
  title = {The Role of Special Districts and Intergovernmental Constraints},
  year = {2023}}
```
