---
title: "The Price of Residential Street Parking"
date: "2020-09-15"
categories: 
    - cities
    - public finance
    - data
---

Cities, broadly, manage a number of public assets with which they provide public services. Some of those services are somewhat passive in the sense that no active labor aside from maintenance is being carried out. And others are more active in that the asset is being used by public sector employees or contractors to provide a public service. We generally think of the latter as the primary mode of public service delivery as it is more visible. We see the bus driver, the police officer, the firefighter, etc in our communities doing their jobs. But the passive service is no less important. We drive on roads, use water and sewer infrastructure (though this is a blended service), etc on a daily basis as we go about our lives. One of the big differences between these two kinds of services is how the public sector asks users to pay for them. Some services are supported through taxes, but a great many are supported through user fees. Below, I point out two approaches to this for getting around a central city: the cost of storing a vehicle on a public street versus the cost of using the transit system.


I choose these two the compare because they are roughly equivalent in their purpose (charging for the use of a public asset, roads v. a transit system), but the mode is different. Undoubtedly, there are private costs here as well. Car owners bear many costs associated with car ownership. Transit riders bear some private costs, mostly in their time, in using the transit system. But what we ask these two user groups to pay for the usage of a public asset is vastly different.

Below is the monthly cost of a residential parking permit[^1] versus the cost of a monthly transit pass for the 30 largest U.S. cities. In nearly every large U.S. city, on-street, residential parking is essentially free. If these residents were to park in a private lot/garage/space (i.e. likely much closer to the market price for parking), it could be many hundreds of dollars per month in parking fees. This suggests the usage of this public asset is being severely underpriced. Meanwhile, public transit passes are significantly more expensive. In many cases, the monthly cost of a residential parking permit is less than a single fare on the central city transit system! While likely not covering the entire cost of public transit, the monthly transit pass is likely covering a much larger proportion of the per user cost of the transit system. It's highly unlikely this is the case for street parking.


```{r}
#| echo: false

library(tidyverse)
library(gt)

tribble(
  ~Rank, ~City,               ~Pop17,   ~MonthlyParkingCost, ~MonthlyTransitPass,
  1L,    "New York City, NY", 8622698L, 0.0,                 127.0,              
  2L,    "Los Angeles, CA",   3999759L, 2.833333333,         100.0,              
  3L,    "Chicago, IL",       2716450L, 2.083333333,         105.0,              
  4L,    "Houston, TX",       2312717L, 2.674166667,         90.0,               
  5L,    "Phoenix, AZ",       1626078L, 0.833333333,         64.0,               
  6L,    "Philadelphia, PA",  1580863L, 2.916666667,         96.0,               
  7L,    "San Antonio, TX",   1511946L, 1.666666667,         38.0,               
  8L,    "San Diego, CA",     1419516L, 0.75,                72.0,               
  9L,    "Dallas, TX",        1341075L, 0.541666667,         96.0,               
  10L,   "San Jose, CA",      1035317L, 2.916666667,         90.0,               
  11L,   "Austin, TX",        950715L,  1.353333333,         41.25,              
  12L,   "Jacksonville, FL",  892062L,  0.0,                 65.0,               
  13L,   "San Francisco, CA", 884363L,  12.0,                81.0,               
  14L,   "Columbus, OH",      879170L,  2.083333333,         62.0,               
  15L,   "Fort Worth, TX",    874168L,  0.0,                 80.0,               
  16L,   "Indianapolis, IN",  863002L,  0.0,                 60.0,               
  17L,   "Charlotte, NC",     859035L,  2.5,                 88.0,               
  18L,   "Seattle, WA",       724745L,  5.416666667,         99.0,               
  19L,   "Denver, CO",        704621L,  0.0,                 114.0,              
  20L,   "Washington, DC",    693972L,  2.916666667,         81.0,               
  21L,   "Boston, MA",        685094L,  0.0,                 90.0,               
  22L,   "El Paso, TX",       683577L,  0.0,                 48.0,               
  23L,   "Detroit, MI",       673104L,  0.0,                 70.0,               
  24L,   "Nashville, TN",     667560L,  0.833333333,         65.0,               
  25L,   "Memphis, TN",       652236L,  0.0,                 NA,                 
  26L,   "Portland, OR",      647805L,  6.25,                100.0,              
  27L,   "Oklahoma City, OK", 643648L,  0.0,                 50.0,               
  28L,   "Las Vegas, NV",     641676L,  0.0,                 65.0,               
  29L,   "Louisville, KY",    621349L,  1.666666667,         50.0,               
  30L,   "Baltimore, MD",     611648L,  1.666666667,         74.0
) |>
  gt() |>
  cols_label(
    Rank = "**Rank**",
    City = "**City**",
    Pop17 = "**2017<br>Population**",
    MonthlyParkingCost = "**Monthly Street<br>Parking Cost**",
    MonthlyTransitPass = "**Monthly Transit<br>Pass Cost **",
    .fn = md
  ) |>
  fmt_integer(columns = c(Rank)) |>
  fmt_number(columns = c(Pop17), decimals = 0, use_seps = TRUE) |>
  fmt_currency(columns = c(MonthlyParkingCost, MonthlyTransitPass)) |>
  sub_missing(columns = c(MonthlyTransitPass), missing_text = "-")

```


In these times of municipal fiscal distress, it is important to consider the costs of providing public services. Since residential street parking is often free (or minimally priced), the cost of upkeep and maintenance of street falls on all taxpayers through general taxation (usually the property tax). This is highly inequitable to non-street parking users who are asked to bear a portion of the cost while receiving no benefits.[^2] The public sector asks transit users to bear a much larger portion of the costs associated with their usage of the public transit infrastructure than car users are asked to bear.

Residential street parking could be a decent revenue source for large cities. Vast sums of money are spent on the provision and maintenance of roads and few mechanisms exist to explicitly capture revenues associated with the usage of roads.[^3] Appropriately pricing residential street parking could do this in a direct way.

tl;dr: Street parking in nearly all U.S. cities is vastly underpriced.

[^1]: It is important to note that in many of these cities the residential parking permit system (or zones) do not cover the entire city. In a great many locations in these cities, street parking is essentially free (or uncharged for by the public sector).
[^2]: This doesn't consider the social costs imposed either.
[^3]: The disconnect between the provision of roads and the revenues to pay for them is and will get worse as the efficiency of the gas tax (the connection between the amount of the tax and the usage of roads) further declines. This is driven by both the failure of the gas tax to be increased (most specifically at the federal level, but also in a number of states) and, paradoxically, the increased popularity of electric or hybrid vehicles that can avoid some or all of the gas tax's intended purpose as a fee on road usage.
